module.exports = [
  {
    id: 1,
    name: "Allegheny",
    image: "./images/default_glassware.png",
    glass: "Martini",
    servings: 1,
    baseIngredient: ["Bourbon"],
    recipe: [
      { id: 1, measureAmount: 1, measureType: "oz.", ingredient: "Bourbon" },
      {
        id: 2,
        measureAmount: 1,
        measureType: "oz.",
        ingredient: "Dry Vermouth",
      },
      {
        id: 3,
        measureAmount: 1.5,
        measureType: "tsps.",
        ingredient: "Blackberry-flavoured Brandy",
      },
      {
        id: 4,
        measureAmount: 1.5,
        measureType: "tsps.",
        ingredient: "Lemon Juice",
      },
    ],
    additionalIngredients: [],
    garnish: ["Twist of Lemon"],
    instructions:
      "Shake with ice and strain into cocktail glass. Add a twist of lemon peel on top.",
  },
  {
    id: 2,
    name: "Singapore Sling",
    image: "./images/default_glassware.png",
    glass: "Collins",
    servings: 1,
    baseIngredient: ["Brandy", "Gin"],
    recipe: [
      { id: 1, measureAmount: 2, measureType: "oz.", ingredient: "Gin" },
      {
        id: 2,
        measureAmount: 0.5,
        measureType: "oz.",
        ingredient: "Cherry-flavoured Brandy",
      },
      {
        id: 3,
        measureAmount: 0.5,
        measureType: "Juice of",
        ingredient: "Lemon",
      },
    ],
    additionalIngredients: ["Club Soda"],
    garnish: ["Seasonal Fruits"],
    instructions:
      "Shake lemon, sugar, and gin with ice and strain into collins glass. Add ice cubes and fill with club soda. Float cherry-flavoured brandy on to. Decorate with fruits in season and serve with straws.",
  },
  {
    id: 3,
    name: "London Buck",
    image: "./images/default_glassware.png",
    glass: "Highball",
    servings: 1,
    baseIngredient: ["Gin"],
    recipe: [
      { id: 1, measureAmount: 2, measureType: "oz.", ingredient: "Gin" },
      {
        id: 2,
        measureAmount: 0.5,
        measureType: "Juice of",
        ingredient: "Lemon",
      },
    ],
    additionalIngredients: ["Ginger Ale", "Ice Cubes"],
    garnish: [],
    instructions:
      "Pour gin and lemon juice over ice cubes in highball glass. Fill with ginger ale and stir.",
  },
  {
    id: 4,
    name: "Bermuda Triangle",
    image: "./images/default_glassware.png",
    glass: "Old-Fashioned",
    servings: 1,
    baseIngredient: ["Rum"],
    recipe: [
      { id: 1, measureAmount: 2, measureType: "oz.", ingredient: "Spiced Rum" },
      {
        id: 2,
        measureAmount: 1,
        measureType: "oz.",
        ingredient: "Peach Schnapps",
      },
      {
        id: 3,
        measureAmount: 3,
        measureType: "oz.",
        ingredient: "Orange Juice",
      },
    ],
    additionalIngredients: ["Ice Cubes"],
    garnish: [],
    instructions: "Pour ingredients into ice filled old-fashioned glass",
  },
  {
    id: 5,
    name: "Heather Blush",
    image: "./images/default_glassware.png",
    glass: "Champagne Flute",
    servings: 1,
    baseIngredient: ["Scotch"],
    recipe: [
      { id: 1, measureAmount: 1, measureType: "oz.", ingredient: "Scotch" },
      {
        id: 2,
        measureAmount: 1,
        measureType: "oz.",
        ingredient: "Strawberry Liqueur",
      },
      {
        id: 3,
        measureAmount: 3,
        measureType: "oz.",
        ingredient: "Chilled Sparkling Wine",
      },
    ],
    additionalIngredients: [],
    garnish: ["Strawberry"],
    instructions:
      "Pour scotch and liqueur into Champagne flute. Top with sparkling wine. Garnish with a strawberry.",
  },
  {
    id: 6,
    name: "South of the Border",
    image: "./images/default_glassware.png",
    glass: "Sour",
    servings: 1,
    baseIngredient: ["Tequila"],
    recipe: [
      { id: 1, measureAmount: 1, measureType: "oz.", ingredient: "Tequila" },
      {
        id: 2,
        measureAmount: 0.75,
        measureType: "oz.",
        ingredient: "Coffee-flavoured Brandy",
      },
      {
        id: 3,
        measureAmount: 0.5,
        measureType: "Juice of",
        ingredient: "Lime",
      },
    ],
    additionalIngredients: [],
    garnish: ["Lime slice"],
    instructions:
      "Shake with ice and strain into sour glass. Add a lime slice.",
  },
  {
    id: 7,
    name: "Jericho Breeze",
    image: "./images/default_glassware.png",
    glass: "Stemmed Goblet",
    servings: 1,
    baseIngredient: ["Vodka"],
    recipe: [
      { id: 1, measureAmount: 1, measureType: "oz.", ingredient: "Vodka" },
      {
        id: 2,
        measureAmount: 0.75,
        measureType: "oz.",
        ingredient: "Blue Curacao",
      },
      {
        id: 3,
        measureAmount: 2.5,
        measureType: "oz.",
        ingredient: "Sour Mix",
      },
      {
        id: 4,
        measureAmount: 1,
        measureType: "splash",
        ingredient: "Lemon-lime Soda",
      },
      {
        id: 5,
        measureAmount: 1,
        measureType: "splash",
        ingredient: "Orange Juice",
      },
    ],
    additionalIngredients: [],
    garnish: ["Pineappe Spear", "Cherry"],
    instructions:
      "Combine ingredients in shaker, shake with ice until frothy. Strain into stemmed goblet. Garnish with a pineapple spear and a cherry.",
  },
  {
    id: 8,
    name: "Irish Shillelagh",
    image: "./images/default_glassware.png",
    glass: "Punch Cup",
    servings: 1,
    baseIngredient: ["Whiskey"],
    recipe: [
      {
        id: 1,
        measureAmount: 1.5,
        measureType: "oz.",
        ingredient: "Irish Whiskey",
      },
      {
        id: 2,
        measureAmount: 1,
        measureType: "tbsp.",
        ingredient: "Sloe Gin",
      },
      {
        id: 3,
        measureAmount: 1,
        measureType: "tbsp.",
        ingredient: "Light Rum",
      },
      {
        id: 4,
        measureAmount: 1,
        measureType: "tsp.",
        ingredient: "Powdered Sugar",
      },
      {
        id: 5,
        measureAmount: 0.5,
        measureType: "Juice of",
        ingredient: "Lemon",
      },
    ],
    additionalIngredients: [],
    garnish: ["Raspberries", "Strawberries", "Cherry", "Peach slices"],
    instructions:
      "Shake with ice and strain into a punch cup. Decorate with raspberries, strawberries, a cherry and peach slices.",
  },
];
